# Generated by Django 4.0.4 on 2025-03-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_alter_play_actors_alter_play_genres'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('performance', 'row', 'seat')},
        ),
    ]
