# Generated by Django 4.0.4 on 2025-03-13 14:48

from django.db import migrations, models
import theatre.models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.play_image_file_path
            ),
        ),
    ]
